IMPORTAMOS LIBRERÍAS

In [2]:
import pandas as pd
import numpy as np
import re
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go

IMPORTAMOS EL CSV DE UBEREATS QUE LIMPIAREMOS

In [31]:
ue = pd.read_csv("../Data/UberEats.csv", index_col = 0)
ue.head(3)

,Restaurante,Valoración,Nota,Delivery_Fee,ETA,Tag,Precio,Dirección,Barrio
0,Badsha India Restaurant,200,4.4,1.00,15–35,India,€,"Calle De Embajadores, 28045",Centro
1,TUTTO PASTA!,26,2.8,2.50,40–60,Family Meals,€,"Calle De Núñez De Arce, 11, 28012",Centro
2,Pizza Central,31,3.8,2.99,35–55,Pizza,€,"Plaza Del Emperador Carlos V, 10, 28012",Centro

In [27]:
for col in ue:
    print(col)
    print(" ")
    print(ue[col].value_counts())
    print("-" * 30)

Restaurante

TUTTO PASTA!               11
Chinawokexpress            10
Badsha India Restaurant     7
Roost Chicken               7
Super Dog                   6
                           ..
Ferreiro                    1
TeKeS                       1
Toropikaru Sushi            1
NUBO Rolls (Norte)          1
Filippo Pizza               1
Name: Restaurante, Length: 316, dtype: int64
------------------------------
Valoración

Valorado con 4.4 de 5 estrellas según más de 200 opiniones.                           21
Valorado con 4.2 de 5 estrellas según más de 200 opiniones.                           19
Valorado con 4.3 de 5 estrellas según más de 200 opiniones.                           14
Valorado con 2.8 de 5 estrellas según 26 opiniones.                                   11
Valorado con 4.1 de 5 estrellas según más de 200 opiniones.                           10
                                                                                      ..
Uno de los restaurantes mejor valorados con 4.8 de 5 estrellas según 78 opiniones.     1
Valorado con 4.4 de 5 estrellas según 194 opiniones.                                   1
Valorado con 4.0 de 5 estrellas según 25 opiniones.                                    1
Valorado con 4.2 de 5 estrellas según 28 opiniones.                                    1
Valorado con 4.1 de 5 estrellas según 12 opiniones.                                    1
Name: Valoración, Length: 158, dtype: int64
------------------------------
Nota

4.2    61
4.3    60
4.6    56
4.4    51
4.5    44
4.1    42
4.8    21
4.0    17
3.9    16
3.7    13
4.9    12
2.8    11
4.7    11
3.8     9
3.6     7
5.0     4
3.2     4
3.0     3
3.5     3
3.4     2
3.3     1
3.1     1
2.9     1
Name: Nota, dtype: int64
------------------------------
Gastos

Los gastos de envío son de 2.40€.         128
Los gastos de envío son de 1.90€.         107
Los gastos de envío son de 1.40€.          93
Los gastos de envío son de 0.90€.          77
Los gastos de envío son de 2.90€.          53
Los gastos de envío son de 0.40€.          19
Los gastos de envío son de Sin precio.     16
Los gastos de envío son de 2.50€.          14
Los gastos de envío son de 3.00€.          13
Los gastos de envío son de 1.00€.          12
Los gastos de envío son de 4.25€.          10
Los gastos de envío son de 2.99€.           8
Los gastos de envío son de 3.40€.           6
Los gastos de envío son de 5.00€.           5
Los gastos de envío son de 2.00€.           3
Los gastos de envío son de 1.99€.           3
Los gastos de envío son de 2.60€.           3
Los gastos de envío son de 3.90€.           2
Los gastos de envío son de 2.49€.           2
Name: Gastos, dtype: int64
------------------------------
Delivery_Fee

Precio de 2.40€    128
Precio de 1.90€    107
Precio de 1.40€     93
Precio de 0.90€     77
Precio de 2.90€     53
Precio de 0.40€     19
Precio de 2.50€     14
Precio de 3.00€     13
Precio de 1.00€     12
Precio de 4.25€     10
Precio de 2.99€      8
Precio de 3.40€      6
Precio de 5.00€      5
Precio de 2.00€      3
Precio de 1.99€      3
Precio de 2.60€      3
Precio de 3.90€      2
Precio de 2.49€      2
Name: Delivery_Fee, dtype: int64
------------------------------
ETA

35–45 min                         88
40–50 min                         84
30–40 min                         70
45–55 min                         69
25–35 min                         46
50–60 min                         40
55–65 min                         30
30–50 min                         28
40–60 min                         21
20–30 min                         20
60–70 min                         20
15–35 min                         18
35–55 min                         11
15–25 min                          9
5–25 min                           7
20–40 min                          3
Abre el Domingo a las 11:30 AM     3
70–80 min                          2
65–75 min                          2
50–70 min                          2
45–65 min                          2
80–90 min                          1
10–30 min                          1
Name: ETA, dtype: int64
------------------------------
Tag

Comida rápida             88
Opciones para alergias    58
Pizza                     48
Alcohol                   46
Pollo                     41
                          ..
Vegetariana                1
Japonesa                   1
Comidas asequibles         1
Cafetería                  1
Aperitivos                 1
Name: Tag, Length: 72, dtype: int64
------------------------------
Precio

€      603
€€      24
€€€      1
Name: Precio, dtype: int64
------------------------------
Dirección

Calle De Embajadores, Madrid, Es, 28045, Community of Madrid 28012    11
Calle De La Alianza 33, Madrid, Es, Comunidad de Madrid 28041         10
Calle Del Pico De La Maliciosa 6, Local, Madrid, EMEA 28038            9
Calle Felipe Fraile 5, Madrid, EMEA 28038                              8
Calle Azulejo 2, Madrid, EMEA 28028                                    8
                                                                      ..
C. Del Dr. Ramón Castroviejo, 59, 28035                                1
Calle Del Aviador Zorita 32, Madrid, EMEA 28020                        1
Calle De Almansa 41, Madrid, EMEA 28039                                1
Calle De Cándido Mateos 21, Madrid, EMEA 28035                         1
Unomas                                                                 1
Name: Dirección, Length: 308, dtype: int64
------------------------------
Barrio

Centro                54
Arganzuela            54
Retiro                54
Salamanca             54
Chamartín             54
Tetuán                54
Chamberí              54
Moncloa-Aravaca       54
Carabanchel           54
Usera                 54
Puente de Vallecas    54
Moratalaz             54
Ciudad Lineal         54
Name: Barrio, dtype: int64
------------------------------

In [15]:
ue["Restaurante"].value_counts()

TUTTO PASTA!               11
Chinawokexpress            10
Badsha India Restaurant     7
Roost Chicken               7
Super Dog                   6
                           ..
Ferreiro                    1
TeKeS                       1
Toropikaru Sushi            1
NUBO Rolls (Norte)          1
Filippo Pizza               1
Name: Restaurante, Length: 316, dtype: int64

In [18]:
ue["Valoración"].value_counts()

Valorado con 4.4 de 5 estrellas según más de 200 opiniones.                           21
Valorado con 4.2 de 5 estrellas según más de 200 opiniones.                           19
Valorado con 4.3 de 5 estrellas según más de 200 opiniones.                           14
Valorado con 2.8 de 5 estrellas según 26 opiniones.                                   11
Valorado con 4.1 de 5 estrellas según más de 200 opiniones.                           10
                                                                                      ..
Uno de los restaurantes mejor valorados con 4.8 de 5 estrellas según 78 opiniones.     1
Valorado con 4.4 de 5 estrellas según 194 opiniones.                                   1
Valorado con 4.0 de 5 estrellas según 25 opiniones.                                    1
Valorado con 4.2 de 5 estrellas según 28 opiniones.                                    1
Valorado con 4.1 de 5 estrellas según 12 opiniones.                                    1
Name: Valoración, Length: 158, dtype: int64

In [19]:
ue["Nota"].value_counts()

4.2    61
4.3    60
4.6    56
4.4    51
4.5    44
4.1    42
4.8    21
4.0    17
3.9    16
3.7    13
4.9    12
2.8    11
4.7    11
3.8     9
3.6     7
5.0     4
3.2     4
3.0     3
3.5     3
3.4     2
3.3     1
3.1     1
2.9     1
Name: Nota, dtype: int64

In [20]:
ue["Gastos"].value_counts()

Los gastos de envío son de 2.40€.         128
Los gastos de envío son de 1.90€.         107
Los gastos de envío son de 1.40€.          93
Los gastos de envío son de 0.90€.          77
Los gastos de envío son de 2.90€.          53
Los gastos de envío son de 0.40€.          19
Los gastos de envío son de Sin precio.     16
Los gastos de envío son de 2.50€.          14
Los gastos de envío son de 3.00€.          13
Los gastos de envío son de 1.00€.          12
Los gastos de envío son de 4.25€.          10
Los gastos de envío son de 2.99€.           8
Los gastos de envío son de 3.40€.           6
Los gastos de envío son de 5.00€.           5
Los gastos de envío son de 2.00€.           3
Los gastos de envío son de 1.99€.           3
Los gastos de envío son de 2.60€.           3
Los gastos de envío son de 3.90€.           2
Los gastos de envío son de 2.49€.           2
Name: Gastos, dtype: int64